#!/bin/bash

_update_pkgs_index(){
    DIR=/home/${USER}/.coenv
    mkdir -p $DIR
    rm -f $DIR/index
    conan search "*" | grep ".*/\([0-9]\.\?\)\+.*" >> $DIR/index
}

_get_pkg_name(){
     echo $1 | grep -o "^[^/]\+"
}


coenv() {
    if [[ "$1" == "update" ]]
    then
        echo "Updating packages index.."
        _update_pkgs_index
        echo "Done.."
    else
        pkg_name=$(_get_pkg_name $1)
        conan install --build=missing --requires $1 -of /tmp/$pkg_name && \
        source /tmp/$pkg_name/conanrun.sh
    fi
}

_get_list_of_pckgs() {
    DIR=/home/${USER}/.coenv
    if [ -f "$DIR/index" ]; then
        remote_pkgs=$(cat $DIR/index)
    else
        remote_pkgs=""
    fi
    local_pckgs=$(conan list "*" | grep ".*/\([0-9]\.\?\)\+.*")
    all_pkgs="$local_pckgs $remote_pkgs update"
    COMPREPLY=($(compgen -W "$all_pkgs" "${COMP_WORDS[1]}"))
}


complete -F _get_list_of_pckgs coenv
