#!/bin/bash

_update_pkgs_index(){
    DIR=/home/${USER}/.coenv
    mkdir -p $DIR
    rm -f $DIR/index
    conan search "*" -r all | sed -e '/Remote.*\:/d' -e '1d' -e '2d' >> $DIR/index
}

_get_pkg_name(){
     echo $1 | grep -o "^[^/]\+"
}


coenv() {
    if [[ "$1" == "update" ]]
    then
        echo "Updating packages index.."
        _update_pkgs_index
        echo "Done.."
    else
        pkg_name=$(_get_pkg_name $1)
        pkg_ref=$1
        if [[ "$pkg_ref" != *@* && "${pkg_ref: -1}" != "@" ]]; then
            pkg_ref="$pkg_ref@"
        fi
        conan install $pkg_ref -if /tmp/$pkg_name -g virtualenv -g virtualrunenv && \
        source /tmp/$pkg_name/activate.sh
        export PS1=$CONAN_OLD_PS1
        source /tmp/$pkg_name/activate_run.sh
        export PS1=$CONAN_OLD_PS1
        export PS1="($pkg_name) $PS1"
    fi
}

_get_list_of_pckgs() {
    DIR=/home/${USER}/.coenv
    if [ -f "$DIR/index" ]; then
        remote_pkgs=$(cat $DIR/index)
    else
        remote_pkgs=""
    fi
    local_pckgs=$(conan search "*" | sed -e '1d' -e '2d')
    all_pkgs="$local_pckgs $remote_pkgs update"
    COMPREPLY=($(compgen -W "$all_pkgs" "${COMP_WORDS[1]}"))
}


complete -F _get_list_of_pckgs coenv
