#!/bin/bash

_show_help(){
     echo "coenv is a bash script to install a conan package and source it's conan run environment."
     echo "Packages can be local, or on remote. To include all remote packages, you need to update"
     echo "the index."
     echo ""
     echo "Commands:"
     echo ""
     echo "update               update remote packages index"
     echo "--help | -h          Show this help message"
     echo ""
}

_update_pkgs_index(){
    DIR=/home/${USER}/.coenv
    mkdir -p $DIR
    rm -f $DIR/index
    conan search -vquiet "*" | grep ".*/\([0-9]\.\?\)\+.*" >> $DIR/index
}

_get_pkg_name(){
     echo $1 | grep -o "^[^/]\+"
}


coenv() {
    if [[ "$1" == "update" ]]
    then
        echo "Updating packages index.."
        _update_pkgs_index
        echo "Done.."
        return
    fi
    if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "help" ]]
    then
        _show_help
        return
    fi    
    pkg_name=$(_get_pkg_name $1)
    conan install --build=missing --requires $1 -of /tmp/$pkg_name && \
    source /tmp/$pkg_name/conanrun.sh

}

_get_list_of_pckgs() {
    DIR=/home/${USER}/.coenv
    if [ -f "$DIR/index" ]; then
        remote_pkgs=$(cat $DIR/index)
    else
        remote_pkgs=""
    fi
    local_pckgs=$(conan list -v quiet -c "*" | grep ".*/\([0-9]\.\?\)\+.*")
    all_pkgs="$local_pckgs $remote_pkgs update help"
    COMPREPLY=($(compgen -W "$all_pkgs" "${COMP_WORDS[1]}"))
}


complete -F _get_list_of_pckgs coenv
